### ISSUE TITLE
Birthday alert manager

### ISSUE THREAD

**Issue by PurpleMyst** [nisamson/glimbot#10]
![Prompt](https://files.catbox.moe/i3qdpw.png)

As per the title and the above image, we should make it pop up with a little message whenever it's someone's birthday so that everybody can celebrate. Also, dates are hard to remember for me.

**Comment by nes77** [comment]
Birthday functionality is nice, but requires collecting and storing PII that I'd rather avoid keeping. If there is some way to implement this functionality without collecting personally identifiable information, I'm open to reconsidering.

**Comment by PurpleMyst** [comment]
Wouldn't it be fine if only each user could register their own birthday? Or you could register _a_ birthday, without specifying whose birthday it is.

**Comment by nes77** [comment]
The problem is that any association between a user ID and a birthday would be collection of PII. Now, having a date associated with a _message_ rather than a user could be fine. That would probably work as a foundation for a reminder module, as well.
